# 应用服务 WEB 访问端口
server:
  port: 8080

# spring配置
spring:
  # 数据库配置
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/budget?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis缓存配置
  redis:
    host: localhost
    port: 6379
  # cache生命周期
  cache:
    redis:
      time-to-live: 86400

# mybatis配置
mybatis:
  configuration:
    #开启小驼峰
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# mybatisPlus配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# slf4j日志配置
logging:
  level:
    com.psd.shop.admin.mapper: DEBUG